name: Auto Merge Dev to Main

on:
  push:
    branches:
      - dev

jobs:
  merge-dev-to-main:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Git user (required for commits)
      - name: Set Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Step 3: Fetch and merge
      - name: Merge dev into main
        run: |
          git checkout main
          git pull origin main
          git merge --no-ff dev -m "Merge dev into main"
          git push origin main
